#!python 
"""
Connect to the proxydispatch on 1901 and issue a shutdown() call over XML-RPC.

The director will shut all parts down in an orderly fashion.

"""
import sys
import socket
from xmlrpclib import Server
from optparse import OptionParser


def main():
    """
    Connect to a directors proxy dispatch and send out a shutdown command.
    """
    parser = OptionParser()    

    parser.add_option("-u", "--uri", action="store", dest="uri", default="http://localhost:1901",
                      help="The uri of the director proxydispatch to connect to.")
    
    (options, args) = parser.parse_args()
    uri = options.uri
    s = Server(uri)
    
    try:
        s.exitall()
        
    except xmlrpclib.ProtocolError, e:
        # ok, the director shut down faster then socket close.
        pass
        
    except socket.error, e:
        sys.stderr.write("Unable to connect on '%s' - %s\n" % (uri, str(e)))
        
    else:
        sys.stdout.write("Exit All called on '%s' OK.\n" % (uri))



if __name__ == "__main__":
    main()

